-- MySQL Script generated by MySQL Workbench
-- ter 14 set 2021 21:23:32
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema s20_labook
-- -----------------------------------------------------
-- Labenu_WFS11S20_LaBok

-- -----------------------------------------------------
-- Schema s20_labook
--
-- Labenu_WFS11S20_LaBok
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `s20_labook` ;
USE `s20_labook` ;

-- -----------------------------------------------------
-- Table `s20_labook`.`s20_labook_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `s20_labook`.`s20_labook_users` (
  `id` VARCHAR(36) NOT NULL,
  `name` VARCHAR(64) NOT NULL,
  `email` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` USING BTREE (`email`) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB
COMMENT = 'Users | Registro de Usuários | Principal e âncora para demais tabelas.';


-- -----------------------------------------------------
-- Table `s20_labook`.`s20_labook_passwords`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `s20_labook`.`s20_labook_passwords` (
  `user_id` VARCHAR(36) NOT NULL,
  `user_password` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`user_id`),
  CONSTRAINT `id`
    FOREIGN KEY (`user_id`)
    REFERENCES `s20_labook`.`s20_labook_users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Passwords | Armazerna passwords hasheados';


-- -----------------------------------------------------
-- Table `s20_labook`.`s20_labook_posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `s20_labook`.`s20_labook_posts` (
  `id` VARCHAR(36) NOT NULL,
  `user_id` VARCHAR(36) NULL,
  `description` TEXT(2000) NOT NULL,
  `create_date` INT NOT NULL,
  `img_link` LONGTEXT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_s20_labook_posts_1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `s20_labook`.`s20_labook_users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Posts | Postagens de usuários | Âncora para Likes e Comments.';


-- -----------------------------------------------------
-- Table `s20_labook`.`s20_labook_likes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `s20_labook`.`s20_labook_likes` (
  `post_id` VARCHAR(36) NOT NULL,
  `user_id` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`post_id`, `user_id`),
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `post_id`
    FOREIGN KEY (`post_id`)
    REFERENCES `s20_labook`.`s20_labook_posts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `s20_labook`.`s20_labook_users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Likes | Curtidas de um Post';


-- -----------------------------------------------------
-- Table `s20_labook`.`s20_labook_comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `s20_labook`.`s20_labook_comments` (
  `id` VARCHAR(36) NOT NULL,
  `user_id` VARCHAR(36) NOT NULL,
  `post_id` VARCHAR(36) NOT NULL,
  `comment` TEXT(2000) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_id_idx` (`user_id` ASC) VISIBLE,
  INDEX `post_id_idx` (`post_id` ASC) VISIBLE,
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `s20_labook`.`s20_labook_users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `post_id`
    FOREIGN KEY (`post_id`)
    REFERENCES `s20_labook`.`s20_labook_posts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Comments | Comentários de um post.';


-- -----------------------------------------------------
-- Table `s20_labook`.`s20_labook_friendships`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `s20_labook`.`s20_labook_friendships` (
  `user_1` VARCHAR(36) NOT NULL,
  `user_2` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`user_1`),
  INDEX `user_id_idx` (`user_1` ASC, `user_2` ASC) VISIBLE,
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_1` , `user_2`)
    REFERENCES `s20_labook`.`s20_labook_users` (`id` , `id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Friendship | Amizades entre usuários\n';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
